# Generated by Django 4.2.7 on 2025-02-26 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_comment_ad_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment cant be less than 3 chars!')], verbose_name='Comment here'),
        ),
    ]
